[[http://melpa.org/#/org-journal][file:http://melpa.org/packages/org-journal-badge.svg]] [[http://stable.melpa.org/#/org-journal][file:http://stable.melpa.org/packages/org-journal-badge.svg]]

* org-journal

  Adapted from http://www.emacswiki.org/PersonalDiary

  Functions to maintain a simple personal diary / journal using in Emacs.
  Feel free to use, modify and improve the code!
  — mtvoid, bastibe

** Synopsis

   =org-journal= is a set of functions and a simple major mode based on =org-mode=. It maintains a set
   of files where each file represents a day. Convenient bindings allow to create journal records in
   the current daily file and search within all records or specified time intervals. All records can
   be browsed and searched from the Emacs Calendar for convenience. All entries in a specified TODO
   state will be carried over to the next day. Optionally, the journal can also be encrypted.

   An example of a daily file (it will actually look a lot nicer, depending on your org-mode
   settings):

#+BEGIN_SRC
  * Tuesday, 06/04/13
  ** 10:28 Company meeting
  Endless discussions about projects. Not much progress

  ** 11:33 Work on org-journal                                   :org-journal:
  For the longest time, I wanted to have a cool diary app on my
  computer. However, I simply lacked the right tool for that job. After
  many hours of searching, I finally found PersonalDiary on EmacsWiki.
  PersonalDiary is a very simple diary system based on the emacs
  calendar. It works pretty well, but I don't really like that it only
  uses unstructured text.

  Thus, I spent the last two hours with making that diary use org-mode
  and represent every entry as an org-mode headline. Very cool!

  ** 15:33 Work on org-journal                                   :org-journal:
  Now my journal automatically creates the right headlines (adds the
  current time stamp if on the current day, does not add a time stamp
  for any other day). Additionally, it automatically collapses the
  headlines in the org-file to the right level (shows everything if in
  view mode, shows only headlines in new-entry-mode). Emacs and elisp
  are really cool!

  ** 16:40 Work on org-journal                                   :org-journal:
  I uploaded my journal mode to marmalade and Github! Awesome!

  ** TODO teach org-journal how to brew coffee                   :org-journal:
#+END_SRC

** Quickstart
   =org-journal= is available through [[http://marmalade-repo.org/][marmalade]], [[http://melpa.milkbox.net/][melpa]] and [[http://melpa-stable.milkbox.net/][melpa-stable]]. So installation should be
   trivial:

#+BEGIN_EXAMPLE
    C-x package-install org-journal
#+END_EXAMPLE

   Doing =C-x org-journal-new-entry= will immediately create a journal directory in the default path
   (customized using the =org-journal-dir= variable), open a file in a specialized mode and insert a
   journal entry template.

   Bindings available in the =org-journal-mode=:

   - =C-c C-f= - to view next entry

   - =C-c C-b= - to view previous entry

   - =C-c C-j= - insert a new entry

   To see available journal entries do =C-x calendar=. Calendar bindings:

   - =j= to view an entry in a new buffer

   - =C-j= to view an entry but not switch to it

   - =i j= to add a new entry

   - =f w= to search in all entries of the current week

   - =f m= to search in all entries of the current month

   - =f y= to search in all entries of the current year

   - =f f= to search in all entries of all time

   - =[= to go to previous entry

   - =]= to go to next entry

** TODO Manual

   customization, agenda vs search, integration, etc

** TODO FAQ
** Contributors

   See [[file:CONTRIBUTORS][CONTRIBUTORS]].

** Changelog

   See [[file:CHANGELOG][CHANGELOG]].
