name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - CHANGELOG
      - CONTRIBUTORS
      - LICENSE
      - MAINTAINERS
      - README.org
      - org-journal.svg

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version:
          - 26.3
          - 27.2
          - 28.2
          - 29.4
          - 30.1
        experimental: [false]
        include:
        - os: ubuntu-latest
          emacs-version: snapshot
          experimental: true
        - os: macos-latest
          emacs-version: snapshot
          experimental: true
        - os: windows-latest
          emacs-version: snapshot
          experimental: true
        exclude:
          - os: macos-latest
            emacs-version: 26.3
          - os: macos-latest
            emacs-version: 27.2

    steps:
    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - uses: actions/checkout@v4

    - name: Run tests
      run: make all
